### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by chenlinying** [GeneZC/StructBias#1]
Traceback (most recent call last):
  File "E:/PycharmProjects/StructBias-main/run.py", line 13, in <module>
    from models import build_model_class
  File "E:\PycharmProjects\StructBias-main\models\__init__.py", line 3, in <module>
    from models.mtl import MTL
ModuleNotFoundError: No module named 'models.mtl'

**Comment by GeneZC** [comment]
Fixed.

**Comment by chenlinying** [comment]
作品已收到

**Comment by chenlinying** [comment]
把这个MTL修改为MUG吗
但是MUG哪个类里面又出现了一个新的错误。里面有个super(MTL)

**Comment by GeneZC** [comment]
Fixed 😂

**Comment by chenlinying** [comment]
作品已收到
